name: CI/CD pipeline
run-name: microservices

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: ./${{ matrix.service }}
      run: npm install

    - name: Run tests
      working-directory: ./${{ matrix.service }}
      run: npm run test

    - name: Build
      working-directory: ./${{ matrix.service }}
      run: npm run build
