name: CI/CD pipeline
run-name: microservices

on: 
  push:
    branches:
      - master

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js for client
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies for client
      working-directory: ./frontend
      run: npm install
      
    - name: Build client
      working-directory: ./frontend
      run: npm run build

  server-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js for server
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies for server
      working-directory: ./backend
      run: npm install
